### ISSUE TITLE
Amazing! But found a bug

### ISSUE THREAD

**Issue by FredrikNoren** [KmolYuan/yaml-peg-rs#7]
Hi,

First of all; this is great! rust-yaml seems to be abandoned so excited to see a new library that can actually handle tags properly.

However I think I found a bug; I tried to pull it in into my project but got the following error:

```
Terminate { name: \"version\", msg: \"1:2\\n%YAML 1.1\\n ^\" }
```

When trying to parse the following yaml file:
[Fir_01_Plant.zip](https://github.com/KmolYuan/yaml-peg-rs/files/8556786/Fir_01_Plant.zip)

**Comment by FredrikNoren** [comment]
@KmolYuan Yeah I noticed that, but I read somewhere that 1.2 is a strict superset of 1.1, so 1.1 should work with a 1.2 parser? Though could be wrong on that. But yeah I tried just setting it to 1.1 but that gave me another error so didn't continue from there.

**Comment by KmolYuan** [comment]
bf005cba45da82130f6033c782ca9fa37e8e4365

**Comment by KmolYuan** [comment]
@FredrikNoren Ok, I can allow YAML 1.1 with a warning message.

**Comment by FredrikNoren** [comment]
@KmolYuan Nice!

**Comment by KmolYuan** [comment]
> Ok, I can allow YAML 1.1 with a warning message.

4cc3e633127d24c7f4637e8219034314afbba04e
